// Package application implements the auth service business logic.
// It orchestrates domain entities and repository operations to fulfill use cases.
package application

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"log"
	"strings"
	"time"

	"forum/internal/modules/auth/domain"
	authPort "forum/internal/modules/auth/ports"
	userPort "forum/internal/modules/user/ports"
	"forum/internal/platform/validator"

	"golang.org/x/crypto/bcrypt"
)

// Service implements the AuthService interface.
// It coordinates authentication operations using domain logic and repositories.
type Service struct {
	sessionRepo     authPort.SessionRepository
	userService     userPort.UserService
	sessionDuration time.Duration
}

// NewService creates a new auth service with the required dependencies.
func NewService(
	sessionRepo authPort.SessionRepository,
	userService userPort.UserService,
	sessionDuration time.Duration,
) *Service {
	return &Service{
		sessionRepo:     sessionRepo,
		userService:     userService,
		sessionDuration: sessionDuration,
	}
}

// Register creates a new user account.
// It validates input, checks for duplicates, hashes the password, and creates a session.
func (s *Service) Register(ctx context.Context, email, username, password string) (userID int, session *domain.Session, err error) {
	// 1. Validate input
	creds := &domain.Credentials{Email: email, Password: password}
	err = ValidateCredentials(creds)
	if err != nil {
		return 0, nil, err
	}

	validation := validator.New()
	validation.Required("username", username)
	if username != "" {
		validation.Username("username", username)
	}
	if !validation.Valid() {
		for field := range validation.Errors() {
			if field == "username" {
				return 0, nil, domain.ErrInvalidUsername
			}
		}
	}

	// Sanitize inputs for storage/lookup
	email = strings.ToLower(strings.TrimSpace(validator.Sanitize(email)))
	username = strings.TrimSpace(validator.Sanitize(username))

	// 2. Check if email or username already exists
	emailExists, err := s.userService.ExistsByEmail(ctx, email)
	if err != nil {
		return 0, nil, err
	}
	if emailExists {
		return 0, nil, domain.ErrEmailAlreadyExists
	}

	usernameExists, err := s.userService.ExistsByUsername(ctx, username)
	if err != nil {
		return 0, nil, err
	}
	if usernameExists {
		return 0, nil, domain.ErrUsernameAlreadyExists
	}

	// 3. Hash the password
	passwordHash, err := s.hashPassword(password)
	if err != nil {
		return 0, nil, err
	}

	// 4. Create user via user service (respects module boundaries)
	userID, err = s.userService.CreateUser(ctx, email, username, passwordHash)
	if err != nil {
		return 0, nil, err
	}

	// 5. Create session for the new user
	sessionToken, err := s.generateSessionToken()
	if err != nil {
		return 0, nil, err
	}

	session = &domain.Session{
		// ID and PublicID will be generated by repository
		UserID:    userID,
		Token:     sessionToken,
		ExpiresAt: time.Now().Add(s.sessionDuration),
		CreatedAt: time.Now(),
		IPAddress: "", // Will be set from request in the HTTP handler
		UserAgent: "", // Will be set from request in the HTTP handler
	}

	err = s.sessionRepo.Create(ctx, session)
	if err != nil {
		return 0, nil, err
	}

	return userID, session, nil
}

// Login authenticates a user with email and password.
// It validates credentials and creates a new session on success.
func (s *Service) Login(ctx context.Context, email, password string) (*domain.Session, error) {
	// 1. Validate input
	creds := &domain.Credentials{Email: email, Password: password}
	err := ValidateCredentials(creds)
	if err != nil {
		return nil, domain.ErrInvalidCredentials
	}

	// Sanitize email for lookup
	email = strings.ToLower(strings.TrimSpace(validator.Sanitize(email)))

	// 2. Retrieve user by email
	user, err := s.userService.GetByEmail(ctx, email)
	if err != nil {
		// If user doesn't exist, return invalid credentials to avoid user enumeration
		return nil, domain.ErrInvalidCredentials
	}

	// 3. Compare password hash using bcrypt
	err = s.comparePassword(user.PasswordHash, password)
	if err != nil {
		return nil, domain.ErrInvalidCredentials
	}

	// 4. If valid, delete any existing sessions for this user (one session per user)
	if err := s.sessionRepo.DeleteByUserID(ctx, user.ID); err != nil {
		log.Printf("WARNING: failed to delete existing sessions for user %d: %v", user.ID, err)
	}

	// 5. Create new session
	sessionToken, err := s.generateSessionToken()
	if err != nil {
		return nil, err
	}

	session := &domain.Session{
		// ID and PublicID will be generated by repository
		UserID:    user.ID,
		Token:     sessionToken,
		ExpiresAt: time.Now().Add(s.sessionDuration),
		CreatedAt: time.Now(),
		IPAddress: "", // Will be set from request in the HTTP handler
		UserAgent: "", // Will be set from request in the HTTP handler
	}

	err = s.sessionRepo.Create(ctx, session)
	if err != nil {
		return nil, err
	}

	return session, nil
}

// Logout invalidates the session with the given token.
func (s *Service) Logout(ctx context.Context, sessionToken string) error {
	// 1. Delete session from repository
	return s.sessionRepo.Delete(ctx, sessionToken)
}

// ValidateSession checks if a session token is valid and not expired.
func (s *Service) ValidateSession(ctx context.Context, sessionToken string) (*domain.Session, error) {
	// 1. Retrieve session by token
	session, err := s.sessionRepo.GetByToken(ctx, sessionToken)
	if err != nil {
		return nil, err
	}

	// 2. Check if session is expired
	if session.IsExpired() {
		// Clean up expired session
		if err := s.sessionRepo.Delete(ctx, sessionToken); err != nil {
			log.Printf("WARNING: failed to delete expired session: %v", err)
		}
		return nil, domain.ErrSessionExpired
	}

	// 3. Return session
	return session, nil
}

// RefreshSession extends the expiration time of an existing session.
func (s *Service) RefreshSession(ctx context.Context, sessionToken string) (*domain.Session, error) {
	// 1. Retrieve session by token
	session, err := s.sessionRepo.GetByToken(ctx, sessionToken)
	if err != nil {
		return nil, err
	}

	// 2. Check if session is expired
	if session.IsExpired() {
		// Clean up expired session
		if err := s.sessionRepo.Delete(ctx, sessionToken); err != nil {
			log.Printf("WARNING: failed to delete expired session: %v", err)
		}
		return nil, domain.ErrSessionExpired
	}

	// 3. Update expiration time
	session.ExpiresAt = time.Now().Add(s.sessionDuration)

	// 4. Save updated session
	err = s.sessionRepo.Update(ctx, session)
	if err != nil {
		return nil, err
	}

	// 5. Return updated session
	return session, nil
}

// GetSession retrieves a session by its token.
func (s *Service) GetSession(ctx context.Context, sessionToken string) (*domain.Session, error) {
	// 1. Retrieve session from repository
	session, err := s.sessionRepo.GetByToken(ctx, sessionToken)
	if err != nil {
		return nil, err
	}

	// 2. Check if session is expired
	if session.IsExpired() {
		// Clean up expired session
		if err := s.sessionRepo.Delete(ctx, sessionToken); err != nil {
			log.Printf("WARNING: failed to delete expired session: %v", err)
		}
		return nil, domain.ErrSessionExpired
	}

	return session, nil
}

// generateSessionToken generates a cryptographically secure session token.
// Uses 32 bytes from crypto/rand (256 bits of entropy) encoded as hex.
func (s *Service) generateSessionToken() (string, error) {
	bytes := make([]byte, 32)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

// hashPassword hashes a plaintext password using bcrypt.
func (s *Service) hashPassword(password string) (string, error) {
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", err
	}
	return string(hash), nil
}

// comparePassword compares a plaintext password with a hash.
func (s *Service) comparePassword(hash, password string) error {
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(password))
}

// ValidateCredentials validates the credentials.
// Returns an error if the credentials are invalid.
func ValidateCredentials(c *domain.Credentials) error {
	v := validator.New()

	v.Required("email", c.Email)
	if c.Email != "" {
		v.Email("email", c.Email)
	}

	v.Required("password", c.Password)
	if c.Password != "" {
		// Minimum 8 characters for secure password validation
		v.Password("password", c.Password, 8)
	}

	if !v.Valid() {
		// Convert validator errors to domain-specific errors
		for field := range v.Errors() {
			switch field {
			case "email":
				return domain.ErrInvalidEmail
			case "password":
				return domain.ErrWeakPassword
			}
		}
	}

	return nil
}
